version: '3.8'

services:
  # Core Frontend Services
  core-banca-web:
    image: ${DOCKER_USERNAME:-andrescarrillo2001}/banquito-core-bancaweb-fronend:latest
    container_name: banquito-core-banca-web
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - banquito
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3

  core-ventanilla-frontend:
    image: ${DOCKER_USERNAME:-andrescarrillo2001}/banquito-core-ventanilla-fronend:latest
    container_name: banquito-core-ventanilla-frontend
    ports:
      - "3001:3001"
    env_file:
      - .env
    networks:
      - banquito
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3001" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  banquito:
    driver: bridge
