name: Deploy Core Backend

on:
  workflow_dispatch:
    inputs:
      service:
        description: "Servicio Core a desplegar (all, core-accounting-service, core-admin-service, core-customer-service, core-account-service, notification-service, identity-access-service, document-service, mailpit)"
        required: true
        default: "all"

  repository_dispatch:
    types: [deploy-core-back]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Core Backend services
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            cd /home/${{ secrets.GCP_VM_USER }}/banquito-infra
            SERVICE="${{ github.event.client_payload.service || github.event.inputs.service }}"
            bash scripts/deploy-core.sh "$SERVICE"
